# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ISiK.Basismodul
canonical: http://simplifier.net/ISiK
name: Basismodul_Stufe1
status: draft
version: 0.2.0
fhirVersion: 4.0.1
# title: Example Title
# description: Example Implementation Guide for getting started with SUSHI
status: draft # draft | active | retired | unknown
version: 1.0.5
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik
  url: https://www.gematik.de
  email: isik@gematik.de
 
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

resources:
  Bundle/example-bw-lab-bundle:
    name: BW Lab Bundle
    description: Composition Bundle containing Lab Order Information for the Botswana HIE
    exampleCanonical: http://b-techbw.github.io/bw-lab-ig/StructureDefinition/bw-lab-composition
  
dependencies:
  hl7.fhir.uv.ips: 1.0.0
  #ihe.mcsd.fhir: dev
    # uri: https://ihe.github.io/ITI.mCSD/index.html
    # version: 0.2.0
  #laboratory.workflows.ig: 0.2.0
    # uri: https://i-tech-uw.github.io/laboratory-workflows-ig/
    # version: 0.2.0
