# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ISiK.Basismodul
canonical: http://simplifier.net/ISiK
name: Basismodul_Stufe1
status: draft
version: 0.2.0
fhirVersion: 4.0.1
# copyright:
copyrightYear: 2021+
releaseLabel: ci-build
title: ISiK Basismodul
description: TODO
#license: CC-BY-SA-4.0
publisher:
  name: gematik
  url: www.gematik.de
  email: isik@gematik.de
  contact: isik@gematik
#jurisdiction:
#  - http://unstats.un.org/unsd/methods/m49/m49.htm#072
#  - urn:iso:std:iso:3166#BW
experimental: true
parameters:
  excludettl: true
 
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

resources:
  Bundle/example-bw-lab-bundle:
    name: BW Lab Bundle
    description: Composition Bundle containing Lab Order Information for the Botswana HIE
    exampleCanonical: http://b-techbw.github.io/bw-lab-ig/StructureDefinition/bw-lab-composition
  
dependencies:
  hl7.fhir.uv.ips: 1.0.0
  #ihe.mcsd.fhir: dev
    # uri: https://ihe.github.io/ITI.mCSD/index.html
    # version: 0.2.0
  #laboratory.workflows.ig: 0.2.0
    # uri: https://i-tech-uw.github.io/laboratory-workflows-ig/
    # version: 0.2.0
