# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ISiK.Basismodul
canonical: http://simplifier.net/ISiK
name: Basismodul_Stufe1
status: draft
version: 0.2.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
title: ISiK Basismodul
description: TODO
publisher:
  name: gematik
  url: www.gematik.de
  email: isik@gematik.de
  contact: isik@gematik
experimental: true
parameters:
  excludettl: true
 
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

dependencies:
  hl7.fhir.uv.ips: 1.0.0
  #ihe.mcsd.fhir: dev
    # uri: https://ihe.github.io/ITI.mCSD/index.html
    # version: 0.2.0
  #laboratory.workflows.ig: 0.2.0
    # uri: https://i-tech-uw.github.io/laboratory-workflows-ig/
    # version: 0.2.0
  de.basisprofil.r4:
    id: basisprofilr4
    uri: https://simplifier.net/guide/basisprofil-de-r4
    version: 1.2.0