Instance: BwIpmsFacilityCodeMap
InstanceOf: ConceptMap
Description: "Mapping between IPMS facility codes and BW MFL codes"
Title: "IPMS Facility Code Mappings" // user-friendly name
Usage: #definition

* insert PublisherContextInstance
* name = "BwIpmsFacilityCodeCM"
* sourceCanonical = Canonical(BwIpmsFacilityCodeVS)
* targetCanonical = Canonical(BwMflFacilityCodeVS)
* group[+].source = Canonical(BwIpmsFacilityCodeVS)
* group[=].target = Canonical(BwMflFacilityCodeVS)

* group[=].element[+].code = #ATMOTCIDCC
* group[=].element[=].target[0].code = #18-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #BMCMAUC
* group[=].element[=].target[0].code = #6-23-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #BOJEIC
* group[=].element[=].target[0].code = #09-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #GGCJULLAB
* group[=].element[=].target[0].code = #15-3-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #HGGMMO
* group[=].element[=].target[0].code = #15-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #HGGNKA
* group[=].element[=].target[0].code = #15-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #MANXOTHP
* group[=].element[=].target[0].code = #12-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #NYANTNO
* group[=].element[=].target[0].code = #16-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #PMANTNO
* group[=].element[=].target[0].code = #15-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XAIRSTC
* group[=].element[=].target[0].code = #08-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XANLESC
* group[=].element[=].target[0].code = #19-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XAREALC
* group[=].element[=].target[0].code = #16-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XAREASC
* group[=].element[=].target[0].code = #16-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XAREAWC
* group[=].element[=].target[0].code = #16-3-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XARTEC
* group[=].element[=].target[0].code = #09-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBAINDPHP
* group[=].element[=].target[0].code = #04-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBAITIC
* group[=].element[=].target[0].code = #08-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBAMALH
* group[=].element[=].target[0].code = #17-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBDFFC
* group[=].element[=].target[0].code = #16-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBDFGLV
* group[=].element[=].target[0].code = #15-3-21
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBDFMALHP
* group[=].element[=].target[0].code = #08-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBDFSPC
* group[=].element[=].target[0].code = #04-2-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBDFSSK
* group[=].element[=].target[0].code = #05-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBDFTHE
* group[=].element[=].target[0].code = #20-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBEETHP
* group[=].element[=].target[0].code = #14-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBEREHP
* group[=].element[=].target[0].code = #07-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBHPMOLC
* group[=].element[=].target[0].code = #00-0-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBLOCK6
* group[=].element[=].target[0].code = #15-3-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBLOCK8
* group[=].element[=].target[0].code = #15-3-25
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBMCCLI
* group[=].element[=].target[0].code = #18-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOATLHP
* group[=].element[=].target[0].code = #05-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOBOPH
* group[=].element[=].target[0].code = #04-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBODIBE
* group[=].element[=].target[0].code = #01-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBODUNHP
* group[=].element[=].target[0].code = #09-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOFKANC
* group[=].element[=].target[0].code = #18-03-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOGOHP
* group[=].element[=].target[0].code = #11-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOIKHU
* group[=].element[=].target[0].code = #16-3-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOIPC
* group[=].element[=].target[0].code = #29-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOITC
* group[=].element[=].target[0].code = #13-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOKAAC
* group[=].element[=].target[0].code = #05-3-01 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOKSC
* group[=].element[=].target[0].code = #11-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBONWHP
* group[=].element[=].target[0].code = #08-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBORAKC
* group[=].element[=].target[0].code = #05-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBORAKNC
* group[=].element[=].target[0].code = #05-3-23
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBORIBC
* group[=].element[=].target[0].code = #05-3-03 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOROHP
* group[=].element[=].target[0].code = #01-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOROLHP
* group[=].element[=].target[0].code = #16-3-26
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOROTC
* group[=].element[=].target[0].code = #04-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOSEIIC
* group[=].element[=].target[0].code = #09-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOSEJAKHP
* group[=].element[=].target[0].code = #01-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOSEJC
* group[=].element[=].target[0].code = #01-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOTAHP
* group[=].element[=].target[0].code = #02-4-22
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOTHHP
* group[=].element[=].target[0].code = #01-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOTLHAPC
* group[=].element[=].target[0].code = #20-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOTSAC
* group[=].element[=].target[0].code = #16-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOTSHC
* group[=].element[=].target[0].code = #19-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOTSWC
* group[=].element[=].target[0].code = #16-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBOYEIC
* group[=].element[=].target[0].code = #01-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBROAD1
* group[=].element[=].target[0].code = #15-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBROAD2
* group[=].element[=].target[0].code = #15-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBROAD3
* group[=].element[=].target[0].code = #15-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBTACLI
* group[=].element[=].target[0].code = #15-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XBUTALHP
* group[=].element[=].target[0].code = #02-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XCHADIC
* group[=].element[=].target[0].code = #08-3-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XCHANGC
* group[=].element[=].target[0].code = #12-3-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XCHANOG
* group[=].element[=].target[0].code = #01-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XCHARLC
* group[=].element[=].target[0].code = #07-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XCHOBHP
* group[=].element[=].target[0].code = #07-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XCWAANHP
* group[=].element[=].target[0].code = #23-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XCWAGAHP
* group[=].element[=].target[0].code = #23-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDADAC
* group[=].element[=].target[0].code = #06-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDAGWHP
* group[=].element[=].target[0].code = #12-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDAMUHP
* group[=].element[=].target[0].code = #04-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDEBORH
* group[=].element[=].target[0].code = #09-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDEKARHP
* group[=].element[=].target[0].code = #07-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDELTMC
* group[=].element[=].target[0].code = #01-1-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDIABOHP
* group[=].element[=].target[0].code = #06-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDIBETHP
* group[=].element[=].target[0].code = #08-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDIGAWC
* group[=].element[=].target[0].code = #23-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDIKGOHP
* group[=].element[=].target[0].code = #09-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDIKHUKHP
* group[=].element[=].target[0].code = #23-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDIKWHP
* group[=].element[=].target[0].code = #09-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDILOHP
* group[=].element[=].target[0].code = #03-4-29
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDILOLHP
* group[=].element[=].target[0].code = #06-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDIMAJW
* group[=].element[=].target[0].code = #29-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDIPHUHP
* group[=].element[=].target[0].code = #20-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDISANHP
* group[=].element[=].target[0].code = #01-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDITLAHP
* group[=].element[=].target[0].code = #02-4-21
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDITLHHP
* group[=].element[=].target[0].code = #23-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDITSC
* group[=].element[=].target[0].code = #20-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDITSHHP
* group[=].element[=].target[0].code = #05-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDITSWC
* group[=].element[=].target[0].code = #22-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDOVEDHP
* group[=].element[=].target[0].code = #08-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDRIEHHP
* group[=].element[=].target[0].code = #11-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XDUTLWHP
* group[=].element[=].target[0].code = #20-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XE&MDADAC
* group[=].element[=].target[0].code = #06-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XEASTHHP
* group[=].element[=].target[0].code = #07-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XERETSHP
* group[=].element[=].target[0].code = #14-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XETSH13C
* group[=].element[=].target[0].code = #14-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XETSHA1HP
* group[=].element[=].target[0].code = #14-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XETSHA6
* group[=].element[=].target[0].code = #14-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XEXTE02
* group[=].element[=].target[0].code = #15-3-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XEXTE14
* group[=].element[=].target[0].code = #15-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XEXTE15
* group[=].element[=].target[0].code = #15-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XEXTE3C
* group[=].element[=].target[0].code = #03-3-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XFIHS
* group[=].element[=].target[0].code = #05-7-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XFPRISO
* group[=].element[=].target[0].code = #16-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGABAHP
* group[=].element[=].target[0].code = #05-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGABAN
* group[=].element[=].target[0].code = #05-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGABWES
* group[=].element[=].target[0].code = #15-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGAKGHP
* group[=].element[=].target[0].code = #05-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGAKHIHP
* group[=].element[=].target[0].code = #11-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGAKUTHP
* group[=].element[=].target[0].code = #05-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGAMAJHP
* group[=].element[=].target[0].code = #23-4-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGAMHP
* group[=].element[=].target[0].code = #02-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGAMODHP
* group[=].element[=].target[0].code = #05-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGANPH
* group[=].element[=].target[0].code = #07-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGANTC
* group[=].element[=].target[0].code = #07-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGATHWHP
* group[=].element[=].target[0].code = #23-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGERALC
* group[=].element[=].target[0].code = #16-3-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGHANHP
* group[=].element[=].target[0].code = #14-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGLOMIS
* group[=].element[=].target[0].code = #01-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGNATAC
* group[=].element[=].target[0].code = #12-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGOBOHP
* group[=].element[=].target[0].code = #04-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGOJWHP
* group[=].element[=].target[0].code = #03-4-30
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGOODHPC
* group[=].element[=].target[0].code = #23-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGOODPH
* group[=].element[=].target[0].code = #23-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGOOSHP
* group[=].element[=].target[0].code = #03-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGOOTHP
* group[=].element[=].target[0].code = #03-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGOSHWC
* group[=].element[=].target[0].code = #12-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGROOTHP
* group[=].element[=].target[0].code = #07-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGUDHP
* group[=].element[=].target[0].code = #14-4-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGULUBHP
* group[=].element[=].target[0].code = #02-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGUMAC
* group[=].element[=].target[0].code = #14-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGUMAPH
* group[=].element[=].target[0].code = #14-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGUNUTHP
* group[=].element[=].target[0].code = #14-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGUNWHP
* group[=].element[=].target[0].code = #02-4-29
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGWETAC
* group[=].element[=].target[0].code = #12-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XGWETPH
* group[=].element[=].target[0].code = #12-2-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XHABUHP
* group[=].element[=].target[0].code = #14-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XHATSHP
* group[=].element[=].target[0].code = #05-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XHEBRON
* group[=].element[=].target[0].code = #23-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XHEREFC
* group[=].element[=].target[0].code = #11-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XHUKUHP
* group[=].element[=].target[0].code = #24-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XHUKUNT
* group[=].element[=].target[0].code = #24-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XHUKUPH
* group[=].element[=].target[0].code = #24-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XHUNHC
* group[=].element[=].target[0].code = #24-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XIKAGOC
* group[=].element[=].target[0].code = #05-3-21
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XIKOGAHP
* group[=].element[=].target[0].code = #14-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XIKONGHP
* group[=].element[=].target[0].code = #08-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XINALEHP
* group[=].element[=].target[0].code = #24-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XINDUSC
* group[=].element[=].target[0].code = #19-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XITHOLHP
* group[=].element[=].target[0].code = #21-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XJACKAHP
* group[=].element[=].target[0].code = #02-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XJACKHP
* group[=].element[=].target[0].code = #02-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XJOOMCL
* group[=].element[=].target[0].code = #01-5-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XJUBIC
* group[=].element[=].target[0].code = #16-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XJUMEDC
* group[=].element[=].target[0].code = #29-3-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XJWANMH
* group[=].element[=].target[0].code = #22-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKACGAHP
* group[=].element[=].target[0].code = #07-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKACHIC
* group[=].element[=].target[0].code = #10-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKADIMC
* group[=].element[=].target[0].code = #03-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKAGIFC
* group[=].element[=].target[0].code = #16-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKAGISC
* group[=].element[=].target[0].code = #19-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKAJAJAHP
* group[=].element[=].target[0].code = #14-4-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKALAKHP
* group[=].element[=].target[0].code = #02-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKALAMC
* group[=].element[=].target[0].code = #08-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKALKFC
* group[=].element[=].target[0].code = #07-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKANG
* group[=].element[=].target[0].code = #24-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKANGWHP
* group[=].element[=].target[0].code = #02-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKANSDH
* group[=].element[=].target[0].code = #06-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKANYMC
* group[=].element[=].target[0].code = #06-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKARAKHP
* group[=].element[=].target[0].code = #07-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKARENG
* group[=].element[=].target[0].code = #01-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKASAH
* group[=].element[=].target[0].code = #10-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKASHP
* group[=].element[=].target[0].code = #10-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKAUDHP
* group[=].element[=].target[0].code = #20-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKAUXHP
* group[=].element[=].target[0].code = #14-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKAVIMHP
* group[=].element[=].target[0].code = #10-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKAZBDFHP
* group[=].element[=].target[0].code = #10-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKAZUNHP
* group[=].element[=].target[0].code = #10-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKEDIAHP
* group[=].element[=].target[0].code = #13-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKEDICL
* group[=].element[=].target[0].code = #03-3-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKENGHP
* group[=].element[=].target[0].code = #21-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKGARIHP
* group[=].element[=].target[0].code = #02-4-25
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKGOMOHP
* group[=].element[=].target[0].code = #09-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKGOMOKHP
* group[=].element[=].target[0].code = #06-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKGOPEHP
* group[=].element[=].target[0].code = #05-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKGOROHP
* group[=].element[=].target[0].code = #23-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKGOSIC
* group[=].element[=].target[0].code = #05-3-05 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKGWATC
* group[=].element[=].target[0].code = #06-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHAKHC
* group[=].element[=].target[0].code = #21-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHAWHP
* group[=].element[=].target[0].code = #11-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHAYAHP
* group[=].element[=].target[0].code = #17-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHEKHP
* group[=].element[=].target[0].code = #20-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHIHP
* group[=].element[=].target[0].code = #11-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHONHP
* group[=].element[=].target[0].code = #21-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHUDC
* group[=].element[=].target[0].code = #20-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHUIHP
* group[=].element[=].target[0].code = #11-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHUMAC
* group[=].element[=].target[0].code = #13-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHURU
* group[=].element[=].target[0].code = #03-3-22
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKHURUHP
* group[=].element[=].target[0].code = #09-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKODIHP
* group[=].element[=].target[0].code = #08-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKOKOHP
* group[=].element[=].target[0].code = #21-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKOKOTHP
* group[=].element[=].target[0].code = #11-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKOLEHP
* group[=].element[=].target[0].code = #07-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKOLHP
* group[=].element[=].target[0].code = #11-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKOMAHP
* group[=].element[=].target[0].code = #01-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKOPON
* group[=].element[=].target[0].code = #05-3-06 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKOTOHP
* group[=].element[=].target[0].code = #20-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKUBANHP
* group[=].element[=].target[0].code = #05-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKUBUNG
* group[=].element[=].target[0].code = #01-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKUDUMHP
* group[=].element[=].target[0].code = #08-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKUKEHP
* group[=].element[=].target[0].code = #07-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKUMAKC
* group[=].element[=].target[0].code = #05-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKUTAMHP
* group[=].element[=].target[0].code = #12-4-27
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKWANBDFHP
* group[=].element[=].target[0].code = #10-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKWEEHP
* group[=].element[=].target[0].code = #13-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XKWENHP
* group[=].element[=].target[0].code = #05-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLAPOLO
* group[=].element[=].target[0].code = #16-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLAZANC
* group[=].element[=].target[0].code = #05-3-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLECHC
* group[=].element[=].target[0].code = #03-3-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLEETHP
* group[=].element[=].target[0].code = #08-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLEHUTHP
* group[=].element[=].target[0].code = #24-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLEKGOHP
* group[=].element[=].target[0].code = #06-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLEKGWHP
* group[=].element[=].target[0].code = #05-4-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLENTC
* group[=].element[=].target[0].code = #05-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLENTSWHP
* group[=].element[=].target[0].code = #04-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLENYBDFHP
* group[=].element[=].target[0].code = #10-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLEPASHP
* group[=].element[=].target[0].code = #12-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLEPHEC
* group[=].element[=].target[0].code = #05-3-08 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLEPHP
* group[=].element[=].target[0].code = #04-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLEPOHP
* group[=].element[=].target[0].code = #23-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLERAC
* group[=].element[=].target[0].code = #03-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLESETC
* group[=].element[=].target[0].code = #17-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLESHHP
* group[=].element[=].target[0].code = #09-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLESILHP
* group[=].element[=].target[0].code = #05-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLESIRC
* group[=].element[=].target[0].code = #05-3-22
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLESOMHP
* group[=].element[=].target[0].code = #10-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLETHCL
* group[=].element[=].target[0].code = #20-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLETLHC
* group[=].element[=].target[0].code = #13-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLETLPH
* group[=].element[=].target[0].code = #13-2-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLETPRISC
* group[=].element[=].target[0].code = #13-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLETSHP
* group[=].element[=].target[0].code = #02-4-23
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLOBATH
* group[=].element[=].target[0].code = #18-1-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLOKGWHP
* group[=].element[=].target[0].code = #24-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLOOLHP
* group[=].element[=].target[0].code = #05-4-25
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLOROLHP
* group[=].element[=].target[0].code = #06-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLORWHP
* group[=].element[=].target[0].code = #23-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLOTLHC
* group[=].element[=].target[0].code = #06-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLOTLHP
* group[=].element[=].target[0].code = #06-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XLOTSAC
* group[=].element[=].target[0].code = #03-3-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAAPEHP
* group[=].element[=].target[0].code = #08-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABABE
* group[=].element[=].target[0].code = #01-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABALHP
* group[=].element[=].target[0].code = #10-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABEC
* group[=].element[=].target[0].code = #03-3-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABELE
* group[=].element[=].target[0].code = #29-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABELHP
* group[=].element[=].target[0].code = #04-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABHP
* group[=].element[=].target[0].code = #04-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABOAHP
* group[=].element[=].target[0].code = #20-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABUDHP
* group[=].element[=].target[0].code = #02-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABUHP
* group[=].element[=].target[0].code = #29-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABULE
* group[=].element[=].target[0].code = #23-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMABUTC
* group[=].element[=].target[0].code = #21-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMACHAC
* group[=].element[=].target[0].code = #08-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMADIAHP
* group[=].element[=].target[0].code = #03-4-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMADIBHP
* group[=].element[=].target[0].code = #08-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMADISHP
* group[=].element[=].target[0].code = #16-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAFITC
* group[=].element[=].target[0].code = #17-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAGAPHP
* group[=].element[=].target[0].code = #12-4-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAGOKHP
* group[=].element[=].target[0].code = #05-4-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAGORHP
* group[=].element[=].target[0].code = #23-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAGOTH
* group[=].element[=].target[0].code = #26-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAHALH
* group[=].element[=].target[0].code = #08-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAHETHP
* group[=].element[=].target[0].code = #05-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAHLC
* group[=].element[=].target[0].code = #15-3-41
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAHOHP
* group[=].element[=].target[0].code = #21-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAHPRIC
* group[=].element[=].target[0].code = #08-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAITEC
* group[=].element[=].target[0].code = #12-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAJWAN
* group[=].element[=].target[0].code = #29-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAJWHP
* group[=].element[=].target[0].code = #03-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKAKC
* group[=].element[=].target[0].code = #09-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKAKU
* group[=].element[=].target[0].code = #01-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKALA
* group[=].element[=].target[0].code = #01-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKALC
* group[=].element[=].target[0].code = #02-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKEHP
* group[=].element[=].target[0].code = #24-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKGOHP
* group[=].element[=].target[0].code = #09-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKOBHP
* group[=].element[=].target[0].code = #16-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKOPC
* group[=].element[=].target[0].code = #11-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKUNHP
* group[=].element[=].target[0].code = #07-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAKWHP
* group[=].element[=].target[0].code = #08-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMALAHP
* group[=].element[=].target[0].code = #03-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMALAT
* group[=].element[=].target[0].code = #29-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMALEHP
* group[=].element[=].target[0].code = #11-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMALOHP
* group[=].element[=].target[0].code = #09-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMALOTHP
* group[=].element[=].target[0].code = #09-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMALWELHP
* group[=].element[=].target[0].code = #20-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAMAHP
* group[=].element[=].target[0].code = #03-4-31
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAMBOHP
* group[=].element[=].target[0].code = #02-4-27
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMANAHP
* group[=].element[=].target[0].code = #03-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMANGAC
* group[=].element[=].target[0].code = #04-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMANTSHW
* group[=].element[=].target[0].code = #20-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMANYAC
* group[=].element[=].target[0].code = #26-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMANYHP
* group[=].element[=].target[0].code = #16-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAOKAC
* group[=].element[=].target[0].code = #22-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAOKC
* group[=].element[=].target[0].code = #03-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAPOKC
* group[=].element[=].target[0].code = #02-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAPOSHP
* group[=].element[=].target[0].code = #12-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMARAHP
* group[=].element[=].target[0].code = #11-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMARAPO
* group[=].element[=].target[0].code = #12-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMASEGO
* group[=].element[=].target[0].code = #16-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMASINHP
* group[=].element[=].target[0].code = #02-4-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMASUKHP
* group[=].element[=].target[0].code = #02-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMASUNC
* group[=].element[=].target[0].code = #02-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMASUPH
* group[=].element[=].target[0].code = #02-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATEBHP
* group[=].element[=].target[0].code = #09-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATENHP
* group[=].element[=].target[0].code = #02-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATHAC
* group[=].element[=].target[0].code = #04-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATHAN
* group[=].element[=].target[0].code = #16-3-25
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATHP
* group[=].element[=].target[0].code = #03-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATLAP
* group[=].element[=].target[0].code = #01-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATLHP
* group[=].element[=].target[0].code = #08-4-27
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATOBHP
* group[=].element[=].target[0].code = #12-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATOHP
* group[=].element[=].target[0].code = #02-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATOLHP
* group[=].element[=].target[0].code = #03-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATSHC
* group[=].element[=].target[0].code = #02-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATSHWC
* group[=].element[=].target[0].code = #01-3-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATSIHP
* group[=].element[=].target[0].code = #12-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMATSIL
* group[=].element[=].target[0].code = #02-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAUBHP
* group[=].element[=].target[0].code = #11-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAUCL
* group[=].element[=].target[0].code = #03-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAUGENC
* group[=].element[=].target[0].code = #01-3-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAUNC
* group[=].element[=].target[0].code = #01-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAUNH
* group[=].element[=].target[0].code = #01-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMAUSSC
* group[=].element[=].target[0].code = #01-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMBALAHP
* group[=].element[=].target[0].code = #02-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMBDFCL
* group[=].element[=].target[0].code = #01-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMEDIEHP
* group[=].element[=].target[0].code = #05-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMETLOC
* group[=].element[=].target[0].code = #23-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMETLOHP
* group[=].element[=].target[0].code = #23-4-26
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMETSIHP
* group[=].element[=].target[0].code = #17-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMETSIM
* group[=].element[=].target[0].code = #05-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMETSIMAHP
* group[=].element[=].target[0].code = #07-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMHALHP
* group[=].element[=].target[0].code = #08-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMIDDLC
* group[=].element[=].target[0].code = #11-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMADIHP
* group[=].element[=].target[0].code = #13-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMADUHP
* group[=].element[=].target[0].code = #16-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMAKHP
* group[=].element[=].target[0].code = #23-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMAMOC
* group[=].element[=].target[0].code = #06-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMANHP
* group[=].element[=].target[0].code = #05-4-21
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMANKC
* group[=].element[=].target[0].code = #05-3-10 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMAPHHP
* group[=].element[=].target[0].code = #08-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMASHC
* group[=].element[=].target[0].code = #03-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMASHO
* group[=].element[=].target[0].code = #29-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMATHC
* group[=].element[=].target[0].code = #09-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMATHE
* group[=].element[=].target[0].code = #23-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMATHP
* group[=].element[=].target[0].code = #05-4-22
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMATSC
* group[=].element[=].target[0].code = #13-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMEYAHP
* group[=].element[=].target[0].code = #13-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMOKOC
* group[=].element[=].target[0].code = #05-3-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMOPAN
* group[=].element[=].target[0].code = #05-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMMUTHP
* group[=].element[=].target[0].code = #08-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOCH1C
* group[=].element[=].target[0].code = #09-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOCHIIC
* group[=].element[=].target[0].code = #09-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOCHPRHP
* group[=].element[=].target[0].code = #09-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMODIHP
* group[=].element[=].target[0].code = #09-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMODIKHP
* group[=].element[=].target[0].code = #03-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOENGHP
* group[=].element[=].target[0].code = #03-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGHP
* group[=].element[=].target[0].code = #03-4-32
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGOBC
* group[=].element[=].target[0].code = #17-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGOBHP
* group[=].element[=].target[0].code = #17-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGODI
* group[=].element[=].target[0].code = #05-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGOHP
* group[=].element[=].target[0].code = #03-4-23
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGOJHP
* group[=].element[=].target[0].code = #23-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGONHP
* group[=].element[=].target[0].code = #26-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGONOHP
* group[=].element[=].target[0].code = #05-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGORHP
* group[=].element[=].target[0].code = #03-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOGOTHP
* group[=].element[=].target[0].code = #14-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOIYAB
* group[=].element[=].target[0].code = #29-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOIYAC
* group[=].element[=].target[0].code = #03-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKATHP
* group[=].element[=].target[0].code = #23-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKGEHP
* group[=].element[=].target[0].code = #08-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKGOMAHP
* group[=].element[=].target[0].code = #23-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKHHP
* group[=].element[=].target[0].code = #22-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKHP
* group[=].element[=].target[0].code = #03-4-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKIBC
* group[=].element[=].target[0].code = #13-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKOBHP
* group[=].element[=].target[0].code = #08-4-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKOHP
* group[=].element[=].target[0].code = #13-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKOKHP
* group[=].element[=].target[0].code = #03-4-22
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKOSWHP
* group[=].element[=].target[0].code = #08-4-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOKUHP
* group[=].element[=].target[0].code = #03-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOLAHP
* group[=].element[=].target[0].code = #04-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOLCOC
* group[=].element[=].target[0].code = #05-3-13 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOLCOEC
* group[=].element[=].target[0].code = #05-3-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOLEHP
* group[=].element[=].target[0].code = #04-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOLEPC
* group[=].element[=].target[0].code = #05-3-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMONOHP
* group[=].element[=].target[0].code = #24-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMONWHP
* group[=].element[=].target[0].code = #20-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOOKAC
* group[=].element[=].target[0].code = #08-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOPIPC
* group[=].element[=].target[0].code = #13-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMORALHP
* group[=].element[=].target[0].code = #08-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMORAMC
* group[=].element[=].target[0].code = #07-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOREHP
* group[=].element[=].target[0].code = #13-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOREOHP
* group[=].element[=].target[0].code = #03-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMORHP
* group[=].element[=].target[0].code = #09-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOROKC
* group[=].element[=].target[0].code = #02-3-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMORUPC
* group[=].element[=].target[0].code = #03-3-06 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMORWAC
* group[=].element[=].target[0].code = #09-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMORWC
* group[=].element[=].target[0].code = #21-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOSHAHP
* group[=].element[=].target[0].code = #06-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOSHAWC
* group[=].element[=].target[0].code = #20-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOSHHP
* group[=].element[=].target[0].code = #08-4-21
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOSHUSDAC
* group[=].element[=].target[0].code = #26-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOSOC
* group[=].element[=].target[0].code = #02-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOSOLHP
* group[=].element[=].target[0].code = #08-4-22
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOSUHP
* group[=].element[=].target[0].code = #13-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOTLHP
* group[=].element[=].target[0].code = #04-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOTLOP
* group[=].element[=].target[0].code = #13-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOTOKWC
* group[=].element[=].target[0].code = #20-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOTSWC
* group[=].element[=].target[0].code = #13-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOWAHP
* group[=].element[=].target[0].code = #02-4-28
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMOWANHP
* group[=].element[=].target[0].code = #08-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMPRISO
* group[=].element[=].target[0].code = #01-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XMULAMHP
* group[=].element[=].target[0].code = #02-4-26
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNATALHP
* group[=].element[=].target[0].code = #16-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNCAAHP
* group[=].element[=].target[0].code = #24-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNCOJAC
* group[=].element[=].target[0].code = #07-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNEWTOC
* group[=].element[=].target[0].code = #03-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNEWXANHP
* group[=].element[=].target[0].code = #07-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNGARHP
* group[=].element[=].target[0].code = #14-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNGWAHP
* group[=].element[=].target[0].code = #08-4-23
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNGWAREC
* group[=].element[=].target[0].code = #20-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNKAIKHP
* group[=].element[=].target[0].code = #17-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNKANGC
* group[=].element[=].target[0].code = #12-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNKOYAC
* group[=].element[=].target[0].code = #05-3-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNLAPHC
* group[=].element[=].target[0].code = #02-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNOKANE
* group[=].element[=].target[0].code = #14-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNSWAZC
* group[=].element[=].target[0].code = #12-3-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNTLHAC
* group[=].element[=].target[0].code = #26-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNTSHEC
* group[=].element[=].target[0].code = #16-3-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNUTRC
* group[=].element[=].target[0].code = #03-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNXAMHP
* group[=].element[=].target[0].code = #14-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNXAUNHP
* group[=].element[=].target[0].code = #14-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XNXOMHP
* group[=].element[=].target[0].code = #14-4-08 
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XOFAMIC
* group[=].element[=].target[0].code = #01-3-21
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XOLIPHC
* group[=].element[=].target[0].code = #09-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XOMAWEHP
* group[=].element[=].target[0].code = #11-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XONALED
* group[=].element[=].target[0].code = #15-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XOODICL
* group[=].element[=].target[0].code = #09-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XORAPAH
* group[=].element[=].target[0].code = #13-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XOTSECL
* group[=].element[=].target[0].code = #17-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XOTSEHP
* group[=].element[=].target[0].code = #08-4-26
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPAJBDF
* group[=].element[=].target[0].code = #29-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPAJCLI
* group[=].element[=].target[0].code = #29-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPALAPH
* group[=].element[=].target[0].code = #03-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPALLAHP
* group[=].element[=].target[0].code = #08-4-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPANDAC
* group[=].element[=].target[0].code = #10-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPANDAMC
* group[=].element[=].target[0].code = #10-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPAPATHP
* group[=].element[=].target[0].code = #23-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPARAKHP
* group[=].element[=].target[0].code = #10-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPELCEC
* group[=].element[=].target[0].code = #18-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPELEAC
* group[=].element[=].target[0].code = #18-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPHAPC
* group[=].element[=].target[0].code = #09-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPHIHEHP
* group[=].element[=].target[0].code = #23-4-23
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPHIMOL
* group[=].element[=].target[0].code = #23-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPHITSHP
* group[=].element[=].target[0].code = #23-4-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPHUDHP
* group[=].element[=].target[0].code = #24-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPHUDUH
* group[=].element[=].target[0].code = #01-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPHUTHC
* group[=].element[=].target[0].code = #05-3-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPHUTIC
* group[=].element[=].target[0].code = #05-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPILANHP
* group[=].element[=].target[0].code = #09-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPILIKC
* group[=].element[=].target[0].code = #08-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPITSAN
* group[=].element[=].target[0].code = #23-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPITSEC
* group[=].element[=].target[0].code = #26-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPLATHP
* group[=].element[=].target[0].code = #10-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPOLANI
* group[=].element[=].target[0].code = #16-5-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPOLEHP
* group[=].element[=].target[0].code = #02-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPOLIC
* group[=].element[=].target[0].code = #17-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPOLOHP
* group[=].element[=].target[0].code = #08-4-25
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPRIKASHP
* group[=].element[=].target[0].code = #10-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPRISHP
* group[=].element[=].target[0].code = #07-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XPRISMACC
* group[=].element[=].target[0].code = #08-3-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XQABOHP
* group[=].element[=].target[0].code = #07-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XQANGC
* group[=].element[=].target[0].code = #14-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRADIC
* group[=].element[=].target[0].code = #03-3-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAILHP
* group[=].element[=].target[0].code = #16-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAILWC
* group[=].element[=].target[0].code = #08-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAKHUHP
* group[=].element[=].target[0].code = #23-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAKMILCC
* group[=].element[=].target[0].code = #23-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAKOPC
* group[=].element[=].target[0].code = #13-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAKOPH
* group[=].element[=].target[0].code = #13-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRALHP
* group[=].element[=].target[0].code = #06-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAMAC
* group[=].element[=].target[0].code = #23-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAMAKC
* group[=].element[=].target[0].code = #02-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAMATBRD
* group[=].element[=].target[0].code = #25-11-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAMOKC
* group[=].element[=].target[0].code = #08-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAMONHP
* group[=].element[=].target[0].code = #09-4-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAMOTHP
* group[=].element[=].target[0].code = #09-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAMSTC
* group[=].element[=].target[0].code = #17-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRANAKAC
* group[=].element[=].target[0].code = #26-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRAPPEHP
* group[=].element[=].target[0].code = #11-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRASHP
* group[=].element[=].target[0].code = #09-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRATHHP
* group[=].element[=].target[0].code = #03-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XROBELHP
* group[=].element[=].target[0].code = #04-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRUNGHP
* group[=].element[=].target[0].code = #05-4-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRUSMAY
* group[=].element[=].target[0].code = #29-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XRUSSEC
* group[=].element[=].target[0].code = #03-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSAKUHP
* group[=].element[=].target[0].code = #17-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSALAC
* group[=].element[=].target[0].code = #20-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSAMAHP
* group[=].element[=].target[0].code = #06-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSANKOY
* group[=].element[=].target[0].code = #01-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSATAUHP
* group[=].element[=].target[0].code = #10-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSCOTIC
* group[=].element[=].target[0].code = #05-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEBELE
* group[=].element[=].target[0].code = #15-3-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEBINC
* group[=].element[=].target[0].code = #12-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSECHEHP
* group[=].element[=].target[0].code = #02-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEDIBHP
* group[=].element[=].target[0].code = #23-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEDIEC
* group[=].element[=].target[0].code = #01-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEFHOC
* group[=].element[=].target[0].code = #04-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEFHPH
* group[=].element[=].target[0].code = #08-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEHERHP
* group[=].element[=].target[0].code = #26-4-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEHITL
* group[=].element[=].target[0].code = #01-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEKGOH
* group[=].element[=].target[0].code = #29-1-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEKHUHP
* group[=].element[=].target[0].code = #23-4-21
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEKOHP
* group[=].element[=].target[0].code = #21-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSELEC
* group[=].element[=].target[0].code = #08-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSELKIC
* group[=].element[=].target[0].code = #02-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSELOHP
* group[=].element[=].target[0].code = #12-4-29
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSELPGH
* group[=].element[=].target[0].code = #19-1-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSELPPCL
* group[=].element[=].target[0].code = #04-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEMBOY
* group[=].element[=].target[0].code = #01-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEMIHP
* group[=].element[=].target[0].code = #12-4-28
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEMOLC
* group[=].element[=].target[0].code = #04-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSENETC
* group[=].element[=].target[0].code = #12-3-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSENYAHP
* group[=].element[=].target[0].code = #02-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEOLWHP
* group[=].element[=].target[0].code = #03-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEPAHP
* group[=].element[=].target[0].code = #12-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEPOC
* group[=].element[=].target[0].code = #14-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSERIHP
* group[=].element[=].target[0].code = #20-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSEROWC
* group[=].element[=].target[0].code = #03-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSERUC
* group[=].element[=].target[0].code = #16-3-23
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSESAMC
* group[=].element[=].target[0].code = #19-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSESE
* group[=].element[=].target[0].code = #22-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSESUHP
* group[=].element[=].target[0].code = #20-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHAAHP
* group[=].element[=].target[0].code = #07-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHADHP
* group[=].element[=].target[0].code = #05-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHAKHP
* group[=].element[=].target[0].code = #08-4-28
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHAKWC
* group[=].element[=].target[0].code = #14-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHASHE
* group[=].element[=].target[0].code = #01-4-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHASHEBHP
* group[=].element[=].target[0].code = #02-4-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHASHMHP
* group[=].element[=].target[0].code = #16-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHASSTHP
* group[=].element[=].target[0].code = #16-4-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHELEC
* group[=].element[=].target[0].code = #08-3-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHORHP
* group[=].element[=].target[0].code = #20-4-13
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHOROC
* group[=].element[=].target[0].code = #01-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSHOSHC
* group[=].element[=].target[0].code = #08-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSIGAC
* group[=].element[=].target[0].code = #17-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSIKWHP
* group[=].element[=].target[0].code = #09-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSIVIYHP
* group[=].element[=].target[0].code = #02-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSOJWEC
* group[=].element[=].target[0].code = #05-3-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSOMELO
* group[=].element[=].target[0].code = #01-4-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSOUTC
* group[=].element[=].target[0].code = #19-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSOWACL
* group[=].element[=].target[0].code = #12-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSTCONC
* group[=].element[=].target[0].code = #17-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSTDCLI
* group[=].element[=].target[0].code = #15-3-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSTJOSE
* group[=].element[=].target[0].code = #15-3-37
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XSTRUIHP
* group[=].element[=].target[0].code = #11-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTAKATOKC
* group[=].element[=].target[0].code = #20-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTAMAHP
* group[=].element[=].target[0].code = #03-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTAPOLC
* group[=].element[=].target[0].code = #19-3-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTATSIC
* group[=].element[=].target[0].code = #02-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTATTOW
* group[=].element[=].target[0].code = #16-3-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTAUPHP
* group[=].element[=].target[0].code = #08-4-29
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTAWANC
* group[=].element[=].target[0].code = #13-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTEBPLMOL
* group[=].element[=].target[0].code = #00-0-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTEWANHP
* group[=].element[=].target[0].code = #08-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTHABAL
* group[=].element[=].target[0].code = #29-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTHALOHP
* group[=].element[=].target[0].code = #12-4-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTHAMAC
* group[=].element[=].target[0].code = #05-3-20
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTHAMPH
* group[=].element[=].target[0].code = #05-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTHANHP
* group[=].element[=].target[0].code = #22-4-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTHEMAC
* group[=].element[=].target[0].code = #02-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTHIIC
* group[=].element[=].target[0].code = #12-3-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTHITOC
* group[=].element[=].target[0].code = #01-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTJUKUHP
* group[=].element[=].target[0].code = #14-4-17
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTLHARESHP
* group[=].element[=].target[0].code = #23-4-22
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTLOKMC
* group[=].element[=].target[0].code = #17-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTLOKWE
* group[=].element[=].target[0].code = #15-3-35
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTLOOWHP
* group[=].element[=].target[0].code = #05-4-23
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTMCOMP
* group[=].element[=].target[0].code = #29-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTOBANEHP
* group[=].element[=].target[0].code = #04-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTONOC
* group[=].element[=].target[0].code = #16-3-22
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTONOCOLC
* group[=].element[=].target[0].code = #16-3-24
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTOPIHP
* group[=].element[=].target[0].code = #03-4-18
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTOROHP
* group[=].element[=].target[0].code = #13-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTOTENG
* group[=].element[=].target[0].code = #01-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSABOC
* group[=].element[=].target[0].code = #11-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSABOPH
* group[=].element[=].target[0].code = #11-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSAMC
* group[=].element[=].target[0].code = #02-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSAUCL
* group[=].element[=].target[0].code = #01-3-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSETSC
* group[=].element[=].target[0].code = #04-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSETSHP
* group[=].element[=].target[0].code = #20-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHANEHP
* group[=].element[=].target[0].code = #24-4-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHAPHP
* group[=].element[=].target[0].code = #24-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHEC
* group[=].element[=].target[0].code = #02-3-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHIDIC
* group[=].element[=].target[0].code = #23-3-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHIHP
* group[=].element[=].target[0].code = #29-4-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHIMC
* group[=].element[=].target[0].code = #22-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHOHP
* group[=].element[=].target[0].code = #04-4-11
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHWAANHP
* group[=].element[=].target[0].code = #20-4-14
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSHWAR
* group[=].element[=].target[0].code = #16-3-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSOKOHP
* group[=].element[=].target[0].code = #12-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSONYHP
* group[=].element[=].target[0].code = #22-4-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTSOPEC
* group[=].element[=].target[0].code = #18-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XTUTUPH
* group[=].element[=].target[0].code = #12-2-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XUKHWHP
* group[=].element[=].target[0].code = #24-4-09
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XUNIT7C
* group[=].element[=].target[0].code = #22-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XVAALHP
* group[=].element[=].target[0].code = #11-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XVERDAC
* group[=].element[=].target[0].code = #11-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XVILLAG
* group[=].element[=].target[0].code = #15-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XWEGHBRHP
* group[=].element[=].target[0].code = #10-3-07
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XWESTHHP
* group[=].element[=].target[0].code = #07-4-08
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XWOODHC
* group[=].element[=].target[0].code = #18-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XXADEHP
* group[=].element[=].target[0].code = #07-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XXAKAOC
* group[=].element[=].target[0].code = #14-3-06
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XXANAGHP
* group[=].element[=].target[0].code = #07-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XXAXAHP
* group[=].element[=].target[0].code = #14-4-16
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XXEREHP
* group[=].element[=].target[0].code = #13-4-12
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XXHOSAC
* group[=].element[=].target[0].code = #08-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XZOROHP
* group[=].element[=].target[0].code = #12-4-03
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XZUTSHHP
* group[=].element[=].target[0].code = #24-4-10
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #XZWENSHP
* group[=].element[=].target[0].code = #02-4-19
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #ZCGABON
* group[=].element[=].target[0].code = #15-3-02
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #ZCGAP02
* group[=].element[=].target[0].code = #15-3-15
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #ZCSPKAS
* group[=].element[=].target[0].code = #29-3-01
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #ZCSPNEW
* group[=].element[=].target[0].code = #29-3-04
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #ZCSPNUT
* group[=].element[=].target[0].code = #29-3-05
* group[=].element[=].target[0].equivalence = #equal
* group[=].element[+].code = #ZCSPSER
* group[=].element[=].target[0].code = #29-3-02
* group[=].element[=].target[0].equivalence = #equal


