name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache fhir cache
        uses: actions/cache@v3
        env:
          cache-name: cache-fhir-packages
        with:
          path: ~/.fhir
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
          #          restore-keys: |
          #            ${{ runner.os }}-build-${{ env.cache-name }}-
          #            ${{ runner.os }}-build-
          #            ${{ runner.os }}-

      - name: Firely.Terminal (GitHub Actions)
        uses: FirelyTeam/firely-terminal-pipeline@v0.3.2
        with:
          PATH_TO_CONFORMANCE_RESOURCES: fsh-generated/resources
          #PATH_TO_EXAMPLES: Examples
          # PATH_TO_QUALITY_CONTROL_RULES: qc/custom
          DOTNET_VALIDATION_ENABLED: true
          JAVA_VALIDATION_ENABLED: false
          # EXPECTED_FAILS: VALIDATION_CONFORMANCE_JAVA VALIDATION_EXAMPLES_JAVA
          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
          SUSHI_ENABLED: true

  test:
    runs-on: ubuntu-latest
    needs: gh-pages
    steps:
      - name: Cache fhir cache
        uses: actions/cache@v3
        env:
          cache-name: cache-fhir-packages
        with:
          path: ~/.fhir
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
            #          restore-keys: |
            #            ${{ runner.os }}-build-${{ env.cache-name }}-
            #            ${{ runner.os }}-build-
            #            ${{ runner.os }}-
      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: ./_updatePublisher.sh --force

      - name: Run sushi to generate the ig.ini file
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: sushi

      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: ./_genonce.sh -no-sushi

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.SECTOKEN }}
#          publish_dir: ./output